/**
 * 챔피언 통계 더미 데이터
 * opponents: 해당 챔피언을 플레이했을 때 상대한 챔피언 목록
 */
export const DUMMY_CHAMPION_STATS = [
  {
    id: 'Jinx',
    name: 'Jinx',
    games: 28,
    wins: 18,
    losses: 10,
    kills: 9.2,
    deaths: 4.1,
    assists: 7.8,
    opponents: [
      { id: 'Caitlyn',    name: 'Caitlyn',    games: 8, wins: 5, losses: 3 },
      { id: 'Jhin',       name: 'Jhin',       games: 6, wins: 4, losses: 2 },
      { id: 'Ezreal',     name: 'Ezreal',     games: 5, wins: 3, losses: 2 },
      { id: 'KogMaw',     name: "Kog'Maw",    games: 4, wins: 2, losses: 2 },
      { id: 'Tristana',   name: 'Tristana',   games: 3, wins: 2, losses: 1 },
      { id: 'Sivir',      name: 'Sivir',      games: 2, wins: 2, losses: 0 },
    ],
  },
  {
    id: 'Caitlyn',
    name: 'Caitlyn',
    games: 22,
    wins: 14,
    losses: 8,
    kills: 8.5,
    deaths: 3.8,
    assists: 9.1,
    opponents: [
      { id: 'Jinx',        name: 'Jinx',        games: 7, wins: 4, losses: 3 },
      { id: 'Jhin',        name: 'Jhin',        games: 5, wins: 3, losses: 2 },
      { id: 'Samira',      name: 'Samira',      games: 4, wins: 2, losses: 2 },
      { id: 'Draven',      name: 'Draven',      games: 3, wins: 2, losses: 1 },
      { id: 'MissFortune', name: 'Miss Fortune', games: 3, wins: 3, losses: 0 },
    ],
  },
  {
    id: 'Thresh',
    name: 'Thresh',
    games: 19,
    wins: 11,
    losses: 8,
    kills: 2.3,
    deaths: 4.7,
    assists: 18.4,
    opponents: [
      { id: 'Lulu',       name: 'Lulu',       games: 6, wins: 3, losses: 3 },
      { id: 'Nautilus',   name: 'Nautilus',   games: 5, wins: 3, losses: 2 },
      { id: 'Blitzcrank', name: 'Blitzcrank', games: 4, wins: 2, losses: 2 },
      { id: 'Leona',      name: 'Leona',      games: 4, wins: 3, losses: 1 },
    ],
  },
  {
    id: 'Ahri',
    name: 'Ahri',
    games: 16,
    wins: 10,
    losses: 6,
    kills: 7.8,
    deaths: 4.2,
    assists: 8.6,
    opponents: [
      { id: 'Zed',      name: 'Zed',      games: 5, wins: 3, losses: 2 },
      { id: 'Syndra',   name: 'Syndra',   games: 4, wins: 2, losses: 2 },
      { id: 'Orianna',  name: 'Orianna',  games: 4, wins: 3, losses: 1 },
      { id: 'Lux',      name: 'Lux',      games: 3, wins: 2, losses: 1 },
    ],
  },
  {
    id: 'LeeSin',
    name: 'Lee Sin',
    games: 14,
    wins: 8,
    losses: 6,
    kills: 6.4,
    deaths: 5.8,
    assists: 10.2,
    opponents: [
      { id: 'Elise',   name: 'Elise',   games: 5, wins: 2, losses: 3 },
      { id: 'Nidalee', name: 'Nidalee', games: 4, wins: 2, losses: 2 },
      { id: 'Hecarim', name: 'Hecarim', games: 3, wins: 2, losses: 1 },
      { id: 'Viego',   name: 'Viego',   games: 2, wins: 2, losses: 0 },
    ],
  },
  {
    id: 'Orianna',
    name: 'Orianna',
    games: 12,
    wins: 9,
    losses: 3,
    kills: 5.8,
    deaths: 2.9,
    assists: 14.3,
    opponents: [
      { id: 'Ahri',   name: 'Ahri',   games: 4, wins: 3, losses: 1 },
      { id: 'Azir',   name: 'Azir',   games: 4, wins: 3, losses: 1 },
      { id: 'Syndra', name: 'Syndra', games: 2, wins: 2, losses: 0 },
      { id: 'Viktor', name: 'Viktor', games: 2, wins: 1, losses: 1 },
    ],
  },
  {
    id: 'Zed',
    name: 'Zed',
    games: 10,
    wins: 5,
    losses: 5,
    kills: 8.9,
    deaths: 6.2,
    assists: 4.1,
    opponents: [
      { id: 'Ahri',       name: 'Ahri',       games: 4, wins: 2, losses: 2 },
      { id: 'Lissandra',  name: 'Lissandra',  games: 3, wins: 1, losses: 2 },
      { id: 'Malzahar',   name: 'Malzahar',   games: 3, wins: 2, losses: 1 },
    ],
  },
];
